services:
  postgres:
    image: postgres
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["postgres", "-c", "port=${POSTGRES_PORT}"]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend: 
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    dns:
      - "8.8.8.8"
    env_file:
      - .env
    volumes:
      - ./server/src:/server/src
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres_data:
