"""unique name for anecdote model

Revision ID: 5e29c50cc816
Revises: 60c1bacb623b
Create Date: 2025-03-26 10:57:21.578830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e29c50cc816'
down_revision: Union[str, None] = '60c1bacb623b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'anecdotes', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anecdotes', type_='unique')
    # ### end Alembic commands ###
