"""Fix tag column

Revision ID: 60c1bacb623b
Revises: 3a8645936fbb
Create Date: 2025-03-21 10:19:37.759511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60c1bacb623b'
down_revision: Union[str, None] = '3a8645936fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anecdotes', 'tag',
               existing_type=postgresql.ENUM('VOVOCHKA', 'JEW', 'CHURCH', 'MOTHER_IN_LAW', 'ALCOHOL', 'ZOO', 'SHTIRLITS', 'OTHERS', name='tags'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anecdotes', 'tag',
               existing_type=postgresql.ENUM('VOVOCHKA', 'JEW', 'CHURCH', 'MOTHER_IN_LAW', 'ALCOHOL', 'ZOO', 'SHTIRLITS', 'OTHERS', name='tags'),
               nullable=False)
    # ### end Alembic commands ###
