"""Create anecdote

Revision ID: 5f30aa1d1150
Revises: 
Create Date: 2025-03-11 13:58:23.403601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f30aa1d1150'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anecdotes',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tag', sa.Enum('VOVOCHKA', 'JEW', 'CHURCH', 'MOTHER_IN_LAW', 'ALCHOGOL', 'ZOO', 'SHTIRLITS', name='tags'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anecdotes')
    # ### end Alembic commands ###
