"""Create anecdote model

Revision ID: 76f3a3fa2e7c
Revises: 
Create Date: 2025-03-20 12:53:26.798403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f3a3fa2e7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anecdotes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tag', sa.Enum('VOVOCHKA', 'JEW', 'CHURCH', 'MOTHER_IN_LAW', 'ALCOHOL', 'ZOO', 'SHTIRLITS', 'OTHERS', name='tags'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anecdotes')
    # ### end Alembic commands ###
